# Generated by Django 2.2.10 on 2020-11-21 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=4096, verbose_name='Message text')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_public_key', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Owner public key')),
                ('opponent_public_key', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Opponent public key')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
